joint_1_lower_limit: -2.8973
joint_1_upper_limit: 2.8973

joint_2_lower_limit: -1.7628
joint_2_upper_limit: 1.7628

joint_3_lower_limit: -2.8973
joint_3_upper_limit: 2.8973

joint_4_lower_limit: -3.0718
joint_4_upper_limit: -0.0698

joint_5_lower_limit: -2.8973
joint_5_upper_limit: 2.8973

joint_6_lower_limit: -3.0175
joint_6_upper_limit: 3.7525

joint_7_lower_limit: -2.8973
joint_7_upper_limit: 2.8973
