zeros:
        panda_joint_1: 0.0318
        panda_joint_2: -1.1042
        panda_joint_3: -0.0637
        panda_joint_4: -2.346
        panda_joint_5: -0.0318
        panda_joint_6: 2.1989
        panda_joint_7: -2.356
