panda_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100


# Only used for manually jogging each axis
panda_joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  constraints: # Parameters taken from franka_control
    goal_time: 0.5
    panda_joint1:
      goal: 0.05
    panda_joint2:
      goal: 0.05
    panda_joint3:
      goal: 0.05
    panda_joint4:
      goal: 0.05
    panda_joint5:
      goal: 0.05
    panda_joint6:
      goal: 0.05
    panda_joint7:
      goal: 0.05
  gains:
    panda_joint1: {p: 1, d: 0, i: 0, i_clamp: 0}
    panda_joint2: {p: 1, d: 0, i: 0, i_clamp: 0}
    panda_joint3: {p: 1, d: 0, i: 0, i_clamp: 0}
    panda_joint4: {p: 1, d: 0, i: 0, i_clamp: 0}
    panda_joint5: {p: 1, d: 0, i: 0, i_clamp: 0}
    panda_joint6: {p: 1, d: 0, i: 0, i_clamp: 0}
    panda_joint7: {p: 1, d: 0, i: 0, i_clamp: 0}


