controller_list:
  - name: $(arg robot_name)/EffortJointInterface_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - $(arg robot_name)_joint_1
      - $(arg robot_name)_joint_2
      - $(arg robot_name)_joint_3
      - $(arg robot_name)_joint_4
      - $(arg robot_name)_joint_5
      - $(arg robot_name)_joint_6
      - $(arg robot_name)_joint_7

  - name: $(arg robot_name)/EffortJointInterface_laparoscope_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - $(arg robot_name)_milc_optics_joint

