manipulator:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005 # rll value 1000
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 3
camera_head_chain:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005 # rll value 1000
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 3
optics_chain:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005 # rll value 1000
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 3
milc_chain:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005 # rll value 1000
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 3
